### ISSUE TITLE
[1.7.10] Conflict with Thermal Expansion's Tesseract and Autopackager

### ISSUE THREAD

**Issue by Whimsyturtle** [MCUpdater/AutoPackager#18]
Crash Report: [http://pastebin.com/Z3cd5un2](http://pastebin.com/Z3cd5un2)

(Submitted on Behalf of ebeck31)

**Comment by smbarbour** [comment]
This appears to be a bug with Tesseracts.  The inventory insertion code where this error is occurring is in CoFHLib (but the actual error that occurred wasn't included in that paste).

I would recommend not using tesseracts as the output inventory for AutoPackagers.  It is unlikely that TeamCoFH will fix this bug, which is occurring in either CoFHLib or ThermalExpansion.
