### ISSUE TITLE
Crash - 1.12.2

### ISSUE THREAD

**Issue by C0rn3j** [MCUpdater/AutoPackager#22]
Whole log containing all the info here, if you need anything else, ask please.

https://paste.c0rn3j.com/?220c2a4b5c7072b7#qFcahAbIsSgenDr8inPezVbcfDqzqPqzxLXqA3mGXRE=

**Comment by smbarbour** [comment]
Fixed by cf798ea791bf05669006ab5c4a244cbb51873ac3
