### ISSUE TITLE
Seems to have issues with Ex Nihilo Aluminum Ingot

### ISSUE THREAD

**Issue by asottile** [MCUpdater/AutoPackager#5]
I'll peek at the code tomorrow, but here's what I'm seeing in game (Agrarian skies 2)

- I have a chest full of Aluminum Ingot (6003)
- Two packagers set to 3x3 (I believe the code calls this LARGE) next to it and powered (I know they're working because other ingots are being crafted)
- None of the aluminum ingots are crafted.

My hypothesis is that this has to do with aluminum ingots *also* having a 2x2 crafting recipe and some bad short-circuiting logic with respect to that. (Empty Canister from Tinker's Construct)

I haven't fiddled, but I imagine the easiest repro would be AutoPackager + Tinker's Construct + Ex Nihilo and reproducing the same situation as above

**Comment by smbarbour** [comment]
The Ex Nihilo aluminium ingot is not valid for making a Block of Aluminum from Tinker's Construct.

**Comment by asottile** [comment]
oh sure enough.  womp. Thanks!
