### ISSUE TITLE
Autopacker + Energy Condenser Mk 2 = crash

### ISSUE THREAD

**Issue by warriorsofcats** [MCUpdater/AutoPackager#6]
I tried to use autopacker to pack the cobblestone that was generated in Energy Condenser Mk 2. That only lead to crash and give me this crash log - http://pastebin.com/Naw8dPUu

If I try to load the world again, it give me this different crash log - http://pastebin.com/EY6C013h

Only work around to get back into the world is to use McEdit to delete either a Energy condenser or a autopacker.

Let me know if you need more.

I just copy and paste this from this Issue in Projecte - https://github.com/sinkillerj/ProjectE/issues/854

**Comment by smbarbour** [comment]
Added code to mitigate against this: 964d3d693e91da5c01283e63c58ef61d91d22a9b
