### ISSUE TITLE
Autopackager lag

### ISSUE THREAD

**Issue by Isolonice** [MCUpdater/AutoPackager#7]
Hello,

autopackager-1.5.4

http://img11.hostingpics.net/pics/649756autopack.png

**Comment by smbarbour** [comment]
What kind of inventory do you have on the input side?

**Comment by Isolonice** [comment]
http://prntscr.com/841ae6
http://prntscr.com/841ag4
http://prntscr.com/841aj7
http://prntscr.com/841ax1

**Comment by smbarbour** [comment]
Yeah... It can be a little heavy on performance when you have three scanning over 300 slots each, every cycle.

**Comment by Isolonice** [comment]
Increasing config values could handle that ?
